export { MainPage } from './src/main/ets/components/MainPage';
export { Course } from './src/main/ets/entity/Course';
export { User } from './src/main/ets/entity/User';
export { Goal } from './src/main/ets/entity/Goal';
export { TrainingPlan } from './src/main/ets/entity/TrainingPlan';
export { ExerciseRecord } from './src/main/ets/entity/ExerciseRecord';
export { Badge } from './src/main/ets/entity/Badge';
export { CheckInRecord } from './src/main/ets/entity/CheckInRecord';
export { VideoPlayProgress } from './src/main/ets/entity/VideoPlayProgress';


