export class RouterKey {
  static VIDEO_PLAYER: string = 'video_player';
  static LOGIN: string = 'login';
  static GOAL_SETTING: string = 'goal_setting';
  static TRAINING_PLAN_LIST: string = 'training_plan_list';
  static PLAN_DETAIL: string = 'plan_detail';
  static CREATE_PLAN: string = 'create_plan';
  static ACTIVE_TRAINING: string = 'active_training';
  static MANUAL_RECORD: string = 'manual_record';
  static BADGE_GALLERY: string = 'badge_gallery';
  static EXERCISE_HISTORY: string = 'exercise_history';
  static MULTI_DEVICE_SYNC: string = 'multi_device_sync';
}
