export { FitnessService } from './src/main/ets/service/FitnessService';
export { UserService } from './src/main/ets/service/UserService';
export { VideoSyncService } from './src/main/ets/service/VideoSyncService';
export { ApiUrls } from './src/main/ets/service/ApiUrls';
export { LibApi } from './src/main/ets/api/LibApi';
// 导出实体类引用
export { HuaweiLoginRequest, HuaweiLoginResponse } from 'lib_entity';

